#pragma once

#include "ShaderConstantInfoDef.h"

/***************************************************************************
* This file is auto generated by ShaderCompiler. Don't modify it manually. *
****************************************************************************/

enum class VertexShaders
{
	PASS_THROUGH,               //From: pass_through_vs.hlsl

	SHADER_COUNT
};

enum class PixelShaders
{
	PASS_THROUGH,               //From: pass_through_ps.hlsl
	PASS_THROUGH_NO_TEX,        //From: pass_through_ps.hlsl
	DEFAULT_MATERIAL,           //From: default_material.hlsl
	DEFAULT_MATERIAL_NO_TEX,    //From: default_material.hlsl

	SHADER_COUNT
};

namespace VsLocalConstant
{
}

namespace PsLocalConstant
{
	namespace PASS_THROUGH
	{
		const LocalConstantPs AMBIENT {0,16};
		const LocalConstantPs DIFFUSE {1,16};
		const LocalConstantPs SPECULAR {2,16};
		const LocalConstantPs EMIT {3,16};
	}
	namespace PASS_THROUGH_NO_TEX
	{
		const LocalConstantPs AMBIENT {0,16};
		const LocalConstantPs DIFFUSE {1,16};
		const LocalConstantPs SPECULAR {2,16};
		const LocalConstantPs EMIT {3,16};
	}
	namespace DEFAULT_MATERIAL
	{
		const LocalConstantPs AMBIENT {0,16};
		const LocalConstantPs DIFFUSE {1,16};
		const LocalConstantPs SPECULAR {2,16};
		const LocalConstantPs EMIT {3,16};
	}
	namespace DEFAULT_MATERIAL_NO_TEX
	{
		const LocalConstantPs AMBIENT {0,16};
		const LocalConstantPs DIFFUSE {1,16};
		const LocalConstantPs SPECULAR {2,16};
		const LocalConstantPs EMIT {3,16};
	}
}

